#!/bin/bash
insta_arquivos1="/etc/adm-server"
insta_arquivos2="/etc/adm-server/adm-ultimate"

rm $(pwd)/$0
apt-get install netpipes -y > /dev/null 2>&1
#===============================#
cor[1]="\033[1;36m"
cor[2]="\033[1;33m"
cor[3]="\033[1;31m"
cor[4]="\033[0m"
#===============================#

instala_fun () {
echo -e "${cor[2]}OK, Instalando..."
echo -e "${cor[1]}=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠"
apt-get install zip -y > /dev/null
apt-get install unzip -y > /dev/null
apt-get install screen -y > /dev/null
apt-get install apache2 -y > /dev/null 2>&1
sed -i "s;Listen 80;Listen 81;g" /etc/apache2/ports.conf
service apache2 restart > /dev/null 2>&1
wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/PROYECTOS_DESCONTINUADOS/master/GENERADOR-ADM-MANAGER-ULTIMATE-FREE/Server/adm-server.tgz > /dev/null 2>&1
wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/PROYECTOS_DESCONTINUADOS/master/GENERADOR-ADM-MANAGER-ULTIMATE-FREE/Server/bin.tgz > /dev/null 2>&1
tar xvfz /root/adm-server.tgz > /dev/null 2>&1
tar xvfz /root/bin.tgz > /dev/null 2>&1
rm -rf /root/adm-server.tgz > /dev/null 2>&1
rm -rf /root/bin.tgz > /dev/null 2>&1
cp -a /root/adm-server/. /etc/adm-server/ > /dev/null 2>&1
cp -a /root/bin/. /bin/ > /dev/null 2>&1
rm -rf /root/adm-server > /dev/null 2>&1
rm -rf /root/bin > /dev/null 2>&1
chmod +x /bin/autoonline > /dev/null 2>&1
chmod +x /bin/keyserver.sh > /dev/null 2>&1
chmod 777 /bin/*
echo -e "${cor[2]} Perfeito, Use o Comando \033[1;31mautoonline ${cor[2]}
 para Gerenciar as Suas Keys e
 Atualizar a Base do servidor"
echo -e "${cor[1]}=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠\033[0m"
rm -rf $HOME/instala_server > /dev/null 2>&1
}

clear
echo -e "${cor[1]}=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠"
echo -e "${cor[3]} INSTALADOR ADM-SCRIPTS ®"
echo -e "${cor[1]}=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠"
echo -e "${cor[3]} Iniciando Instalação..."
echo -e "${cor[1]}=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠=≠"
echo -ne "${cor[4]}"
instala_fun
